version: '3.8'
services:
  front:
    container_name: react-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/react-app
      - node_modules_volume:/react-app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  node_modules_volume:
    driver: local
